language: go

go:
 - tip

env:
    - GIMME_OS=linux GIMME_ARCH=amd64

install:
    - export GOPATH=$(pwd)
    - cd src/atlassian-test
    - go get -d -v ./...

script:
    - cd src/atlassian-test
    - go build -v ./...
